# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!


def available_pods
  pod 'AFNetworking', '~> 3.0.4'
  pod 'RealmSwift', '~> 0.97.0'
  pod 'SnapKit', '~> 0.15.0'
  pod 'CVCalendar', '~> 1.2.8'
  pod 'SwiftyJSON', '~> 2.3.2'
  pod 'Locksmith', '~> 2.0.5'
  pod 'ActionSheetPicker-3.0', '~> 2.0.4'
  pod 'SCRecorder', '~> 2.6.1'
  pod 'R.swift', '~> 1.3.0'
  pod 'Toucan', '~> 0.5.0'
  pod 'HCSStarRatingView', :git => 'https://github.com/reigndesign/HCSStarRatingView.git', :commit => '009f3ba401a'
  pod 'TTTAttributedLabel', '~> 1.13'
end

target 'fiti' do
    available_pods
end

target 'fiti-prod' do
    available_pods
end
